sros/docker/Dockerfile, sros/docker/launch.py
this PR changes the way management interface of SR OS is provisioned to make room for configuration persistency.
Originally vrnetlab used `user` netdev of qemu with an embedded tftp server. Unfortunately, the embedded server doesn't allow writing files to it, thus it was impossible to configure SR OS to persists its configuration on such tftp server.
This PR changes the way management interface is created. It now uses a bridge interface connected to `br-mgmt` bridge created on demand.
Since by using bridge interface we are moving into host network namespace, we chose to use a rare subnetwork used to address bridge interface and SR OS management tap interface connected to it: `172.31.255.28/30`
This is done to minimize the chance that this network will affect hosts routing.
Also, since the …
=> added support for config persistency for sros

common/vrnetlab.py, sros/docker/launch.py
SR OS nodes do not require default socat rules routed via 127.0.0.1, as we do not use host networking
Since these default socat processes were called, we had an issue with SNMP rule doubled and blackholed
=> make possible to disable default socat rules

sros/docker/Dockerfile, sros/docker/launch.py
this PR adds metadata argument for SR OS images
the metadata is a list of arguments that higher level system can pass to vrnetlab
the first metadata arguement is docker-net-v4-addr which informs which network address is used by docker for management. This argument is currently used in SR OS router to configure bof static address to reach the management network
=> Docker net addr

.gitignore, sros/docker/Dockerfile, sros/docker/launch.py
all tcp ports were forwarded from container eth0 interface to sros management interface.
This prevented access to sros serial interface (tcp/5000) from outside the container
This PR adds a change to the iptables forwarding rules so that tcp/5000 is exluded from port forwarding to sros management interface.
=> exluded tcp 5000 port from forwarding to sros management to enable telnet access

csr/README.md, csr/docker/Dockerfile, csr/docker/launch.py
Fixes #43 
Update to CSR 1000v files for support with containerlab
- Updated Dockerfile from debian Stretch to Ubuntu 20.04, added additional packages similar to done with other updated components
- added hostname, nics, and conn_mode flags to launch.py
- added delay to gen_nics, without it, interfaces would not reliably appear on images
- added nic_type to CSR class specifying virtio, default of e1000 not supported with current  CSR ios.
- updated README to indicate tested version 17.03.02
tests with versions 16.12 and 16.11 both failed as gig1 was not created
=> update Cisco CSR 1000v for support with containerlab

common/vrnetlab.py, csr/docker/launch.py, nxos/docker/launch.py, pan/docker/launch.py, sros/docker/launch.py, veos/docker/launch.py, xrv9k/docker/launch.py
sorry, was a bit premature on the last one...
- sets num nics to the same quantity as shows up in the pan web ui
- fix hostname (had left it as xrv9k)
- make the setting of the uuid nicer
- add the delay (copied from csr) so that the syscall(?!) magic happens prior to the nics getting generated (for containerlab)
will open containerlab pr shortly, I guess maybe hold off on merging this till you have time to make sure I don't need to make any more updates here to work nicer with containerlab?
carl
=> Palo fixes

common/vrnetlab.py
lets us provision interfaces however we want in containerlab. basically allocates "dummy" interfaces up to the highest user provisioned interface.
is it ever possible for a file/dir name starting with "eth" in /sys/class/net to be anything but eth1, eth9, eth99 etc. (as in eth + some digits)? there's a probably fragile down and dirty regex to just yoink out the digits from those eth objects so we know the "highest provisioned interface" number.
fairly messy, but functional. gen_nics should probably get a little re-write love at some point :)
=> first draft non contiguous interface allocation

sros/docker/launch.py
This PR does an unmentionable thing and adds the required NAT rules to get IPv6 running in Containerlab. In the future, I would love to modify containerlab to control the linux bridge addressing so that we can do routing, however, that will require a lot more work and change a LOT of patterns, so I just stuck to NATting/PATing IPv6. 
A few notes about the changes:
* Redefines v4 constants in `launch.py` to be AF specific.
* Adds new constants in `launch.py`.
* Adds required SR-OS commands to assign a v6 address in the BOF.
* Enables IPv6 Forwarding (and general usage) in the host container kernel via `run_command` sysctl modifications.
* Adds v6 address to br-mgmt bridge.
* Adds NAT rules to allow access in and out of the SR-OS VM. 
Let me know what you think!
=> feat: Add IPv6 Support to vr-sros

routeros/docker/launch.py
Some newer versions of Mikrotik made changes to the prompts/login.
6.48 changed to using RouterOS instead of MikroTik for the prompts
7.1 requires setting the password on 1st login
This fixes it for the various versions
=> Fixed RouterOS issues found in newer versions (6.48.5 and 7.1)

n9kv/Makefile
As the title suggests, this PR adds support for 7.x, multi-digit 9.x, and 10.x Nexus 9000v/9300v/9500v software images by enhancing the regular expression pattern used to extract the NX-OS software version (which is subsequently used to tag Nexus 9000v/9300v/9500v Docker images). The lack of support for these images was reported in #75.
This has been tested on a variety of image files through the following shell commands:
```shell
christopher@ubuntu-vm:~$ echo nxosv-final.7.0.3.I7.5a.qcow2 | sed -e 's/.\+\?\.\(\(7\.0\.3\.I[0-9]\.[0-9a-z]\+\)\|\([0-9]\+\.[0-9]\+\.[0-9]\+\)\)\(\..*\|$$\)/\1/'
7.0.3.I7.5a
christopher@ubuntu-vm:~$ echo nxosv-final.7.0.3.I7.9.qcow2 | sed -e 's/.\+\?\.\(\(7\.0\.3\.I[0-9]\.[0-9a-z]\+\)\|\([0-9]\+\.[0-9]\+\.[0-9]\+\)\)\(\..*\|$$\)/\1/'
7.0.3.I7.9 …
```
=> Add support for 7.x, multi-digit 9.x, and 10.x Nexus 9000v versions

n9kv/docker/launch.py
The current n9kv launch.py does not wait for the bootstrap_config()'s "copy running-config startup-config" to complete before launching startup_config(). This causes startup_config() to begin issuing commands to the switch, sensing the copy animation's "#" as the wait_send(wait="#") blocking character. This causes any startup-config provided via CLAB yaml to be applied pre-maturely, leading to not applying the beginning config stanzas of the startup config. 
I have confirmed this fork fixes the issue by adding ```self.wait_write("! Bootstrap config for ContainerLab Complete.", wait="Copy complete.")``` to the end of the bootstrap_config() method, causing the method to block until the switch registers the "copy" action complete.
More Details:
The output of Cisco Nexus "copy" command:
``` …
```
=> n9kv - Fix Racing of Bootstrap/Startup Config Apply

xrv9k/docker/launch.py
fix #86 by setting 16GB mem by default. Previous mem limit of 12GB didn't let newer xrv9k to boot in time.
=> set default mem for xrv to 16GB

common/vrnetlab.py, sros/docker/launch.py
ref #37 
this PR adds intial support for multi line card images. These are the images that have multiple SROS_lc VMs defined.
The code allows to define multi-lc VMs like that:
```yaml
name: sros-test
topology:
nodes:
sr1:
kind: vr-sros
image: vrnetlab/vr-sros:21.2.R1
license: license-sros21.txt
type: |
cp: cpu=4 ram=4 chassis=sr-2s slot=A card=cpm-2s ___
lc: cpu=2 ram=4 max_nics=8 chassis=sr-2s slot=1 card=xcm-2s xiom/x1=iom-s-1.5t mda/x1/1=ms2-400gb-qsfpdd+2-100gb-qsfp28 ___
lc: cpu=2 ram=4 max_nics=8 chassis=sr-2s slot=2 card=xcm-2s xiom/x1=iom-s-1.5t mda/x1/1=ms2-400gb-qsfpdd+2-100gb-qsfp28
```
The problem is that additional work is needed here to make qemu strings for different SROS_lc VMs. At this point, if you attach `eth1` interface to that node, it will try to create `tap1` …
=> initial support for multi-lc sros images

sros/docker/launch.py
A fix for embedded variants issue.
I extract _parser function with name parse_variant_line to become public function and not an internal function of parse_custom_variant.
I reuse parse_variant_line to get slot information from lc timos_line.
=> Parse embedded variants in case of no slot definiton

sros/docker/launch.py
tested on 21.10.R3 and 22.10.R1
=> add VSR-I chassis type to support network functions based on the isa card 

ocnos/Makefile, ocnos/README.md, ocnos/docker/Dockerfile, ocnos/docker/launch.py
- Support for IPInfusion OcNOS
The [introduction of OcNOS by containerlab](https://containerlab.dev/manual/kinds/ipinfusion-ocnos/) stated that the image was supported by boxen, but the OcNOS 6.x series, which is currently available for download from the official site, did not seem to be supported.
- Serial console issues
The image of OcNOS version 6.0.2.11 distributed from the official website has a bug that prevents connection via serial console.
Therefore, the officially distributed image cannot be used as is and a workaround is provided in the documentation.
I have informed the vendor of this problem, but do not know when a fix will be provided.
=> Add support for IPInfusion OcNOS

common/vrnetlab.py
Currently, `gen_mac()` generates a mac address in the qemu OUI space (`52:54`) -- a very sensible and responsible decision. 
However, mac addresses starting with 52 cause a crash of the MLAG process in Arista vEOS, as it's unable to generate a virtual mac address. The same issue was experienced in the GNS3 project when they too moved to the qemu OUI space: https://github.com/GNS3/gns3-gui/issues/2475
I propose an equivalent solution: moving to a `0C:` prefixed mac address.
=> refactor: replace oui for base mac generation

sros/Makefile, sros/docker/launch.py
Starting with SR OS 23.3 nodes boot with MD-CLI by default.
This PR adds support for MD-CLI provisioning
=> Model driven SR OS support (SR OS >=23.3)

common/vrnetlab.py, sros/docker/launch.py
* By default, wait for the full prompt "# " (space after #) instead of just '#' - as there are status messages that contain '#' too (without space)
* After some commands (e.g. quit-config) there are characters left to read, causing subsequent commands to go out of sync. Gobble up any remaining characters
=> Update vrnetlab.py - improve Telnet sync on 23.3.R1

sros/docker/launch.py
The '10.0.0.0/24' subnet was raising questions about potential overlap, 'restrict' further limits the connectivity
=> Update launch.py - clarify dummy mgmt nic

aoscx/Makefile, aoscx/README.md, aoscx/docker/Dockerfile, aoscx/docker/launch.py
Support for ArubaOS-CX virtual switches.
*Brutally* tested also on containerlab with the following topology:
```
name: test-aoscx
mgmt:
ipv4-subnet: 192.168.124.0/24
topology:
nodes:
r1:
mgmt-ipv4: 192.168.124.101
kind: vr-veos
image: vrnetlab/vr-aoscx:20230531220439
runtime: docker
r2:
mgmt-ipv4: 192.168.124.102
kind: vr-veos
image: vrnetlab/vr-aoscx:20230531220439
runtime: docker
links:
- endpoints:
- "r1:eth1"
- "r2:eth1"
```
=> Support for ArubaOS CX

config-engine-lite/Dockerfile, ftosv/docker/Dockerfile, n9kv/docker/Dockerfile, nxos/docker/Dockerfile, ocnos/docker/Dockerfile, pan/docker/Dockerfile, routeros/docker/Dockerfile, routeros/docker/launch.py, sros/docker/Dockerfile, sros/docker/launch.py, veos/docker/Dockerfile, vmx/docker/Dockerfile, vsrx/docker/Dockerfile, xrv/docker/Dockerfile, xrv9k/docker/Dockerfile
iptables backend is sunsetting in major for major OS release (Debian and RHEL derivatives are the user base for containerlab). This causes issues for OSes that don't have iptables kernel support, e.g. Rocky9. This results in errors to create iptables rules - see [chat](https://discord.com/channels/860500297297821756/865574858385784842/1123162654949769287).
This PR adds nftables package to ubuntu base so that iptables-nft CLI can be used as a drop-in replacement for iptables manipulation.
As a consequent change, the iptables command is switched to iptables-nft in the launch scripts for nodes which tune iptables rules.
=> deprecate iptables backend in favor of nftables

common/vrnetlab.py
Revert change to skip empty commands, some platforms rely on this (one could argue they should use '\r' to send <enter>, but...)
Addresses https://github.com/hellt/vrnetlab/issues/130
=> Remove change to skip empty commands

common/vrnetlab.py
This imports the work from @mzagozen's commit
8f697f64a9597c11b788dfb5659cfe6c8bfcc185 in vrnetlab/vrnetlab. The added logic is needed to facilitate the lack of automatic backing image format detection in newer versions of QEMU.
Implemented in https://github.com/vrnetlab/vrnetlab/pull/326 following the discussion in https://github.com/vrnetlab/vrnetlab/pull/323.
I tried to cherry-pick the original commit but unfortunately the divergence was too big.
=> Set backing image format

Makefile, README.md, config-engine-lite/configengine, topology-machine/topomachine, vjunosswitch/Makefile, vjunosswitch/README.md, vjunosswitch/docker/Dockerfile, vjunosswitch/docker/juniper.conf, vjunosswitch/docker/launch.py, vjunosswitch/docker/make-config.sh
This is a PR to add support for Juniper's vJunos-switch image that emulates an EX2914. vJunos Labs is a recent initiative that features lab images vJunos-switch and vJunosEvolved, the latter I am working out some kinks and will add this in a later PR. I used the below topology file with containerlab for testing. Once this is verified and upstream for vrnetlab I will make the PR for containerlab as well.
```yaml
name: demo
topology:
nodes:
n1:
kind: srl
image: ghcr.io/nokia/srlinux
startup-config: srl.cfg
vswitch0:
kind: vr-vjunosswitch
image: vrnetlab/vr-vjunosswitch:23.2R1.14
startup-config: vjunos.cfg
links:
- endpoints: ["n1:e1-1", "vswitch0:eth1"]
```
The existing Juniper nodes (vSRX, vMX, vQFX) feature some send/wait type logic on the Junos CLI to configure the nodes with their bare …
=> adding support for vJunos-switch

Makefile, README.md, common/vrnetlab.py, openbsd/Makefile, openbsd/README.md, openbsd/docker/Dockerfile, openbsd/docker/backup.sh, openbsd/docker/launch.py, openbsd/download.sh
This is a PR to add OpenBSD support. OpenBSD can run various routing protocols out-of-the-box and ships with the PF packet filter, making it suitable for use as a router or firewall.
I tested this image with the below `containerlab` topology.
```yaml
name: vobsd1
topology:
nodes:
obsd1:
kind: openbsd
image: vrnetlab/vr-openbsd:7.3
client1:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.1.2/30 dev eth1
- ip route add 192.168.2.0/30 via 192.168.1.1
client2:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.2.2/30 dev eth1
- ip route add 192.168.1.0/30 via 192.168.2.1
links:
- endpoints: ["obsd1:eth1", "client1:eth1"]
- endpoints: ["obsd1:eth2", "client2:eth1"]
```
I implemented the configuration save and restore with …
=> Initial OpenBSD support

sros/docker/launch.py
Hi, 
Adding fixes for pre-defined and broken types for kind `nokia_sros`:
- `sr-7s-fp4`  had twice more fsms than supported by chassis
- `sr-1e-sec` had wrong definition for lcs
- `sr-a4` had wrong definition for lcs
=> Fixes for pre-defined nokia_sros models

asav/Makefile, asav/README.md, asav/docker/Dockerfile, asav/docker/launch.py
Hi all,
This PR is to add support for Cisco ASAv, I've build and tested this with the asav9-18-2.qcow2 image that is available from Cisco CML / VIRL.
I'd like to add it to this project so it hopefully can also be supported in https://github.com/srl-labs/containerlab
Terminal output where you can see the build:
```
root@containerlab:/home/stimmerman/vrnetlab/asav# make docker-image
../makefile-install.include:32: warning: overriding recipe for target 'docker-pre-build'
../makefile.include:18: warning: ignoring old recipe for target 'docker-pre-build'
for IMAGE in asav9-18-2.qcow2; do \
echo "Making $IMAGE"; \
make IMAGE=$IMAGE docker-build; \
done
Making asav9-18-2.qcow2
make[1]: Entering directory '/home/stimmerman/vrnetlab/asav'
../makefile-install.include:32: warning: overriding recipe …
```
=> Initial ASAv support

Makefile, README.md, ftdv/Makefile, ftdv/README.md, ftdv/docker/Dockerfile, ftdv/docker/launch.py
This is a PR to add Cisco FTDv support.
I tested this image with the below `containerlab` topology.
```yaml
name: ftdv01
topology:
nodes:
ftdv1:
kind: vr-ftdv
image: vrnetlab/vr-ftdv:7.2.5
client1:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.1.2/30 dev eth1
- ip route add 192.168.2.0/30 via 192.168.1.1
client2:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.2.2/30 dev eth1
- ip route add 192.168.1.0/30 via 192.168.2.1
links:
- endpoints: ["ftdv1:eth1", "client1:eth1"]
- endpoints: ["ftdv1:eth2", "client2:eth1"]
```
Once this is approved and verified I will create a PR for `containerlab` as well.
=> Initial Cisco FTDv support

vjunosswitch/docker/launch.py
Allow a host with an AMD CPU to spin up vjunos-switch within a nested virtualisation setup.
Did originally try `host` however vjunos-switch instance wouldn't boot, it gets as far as "Creating initial configuration..."  before a qemu prompt is seen where it then loops waiting for the VM to boot.
=> Allow a host with an AMD CPU to spin up vjunos-switch within a nested virtualisation setup

common/vrnetlab.py, sros/docker/launch.py
2 changes:
- Added support for extra CF disks on vr-sros (custom variant).
- Switched qemu drive if from 'ide' to 'virtio' since this is the officially supported option and also faster.
Usage: add cfX=SIZE on cp: line., where
X=the id of CF slot (1 or 2)
SIZE=the size of the disk to be created in case it doesn't exist. This is passed directly to qemu-img create if new disk needs to be created. Otherwise, an already existing disk is reused without modification.
The disks are located inside /tftpboot/, so they are easily accessible from the host and survive destroy operation.
node config sample:
r01:
kind: vr-sros
type: >- 
cp: cpu=2 ram=4 cf1=1G cf2=2G chassis=SR-7 slot=A card=cpm5 ___
lc: cpu=2 ram=4 max_nics=10 chassis=SR-7 slot=1 card=iom4-e-b mda/1=me10-10gb-sfp+
tftpboot directory …
=> SROS: added support for extra CF disks (custom variant). switched qemu drive if to virtio

sros/docker/launch.py
better alignment with SR Linux using containerlab
=> Enable SNMPv2 read-only community public by default

sros/README.md, sros/docker/launch.py
Hi, new cool toy has arrived in 23.10.R3.
```
name: e2c
topology:
nodes:
ixr-e2c:
kind: nokia_sros
image: vrnetlab/vr-sros:23.10.R3
type: ixr-e2c
license: license.txt
```
```
A:admin@ixr-e2c# show system information
===============================================================================
System Information
===============================================================================
System Name            : ixr-e2c
System Type            : 7250 IXR-e2c
Chassis Topology       : Standalone
System Version         : B-23.10.R3
Crypto Module Version  : SRCM 4.2
System Contact         :
System Location        :
System Coordinates     :
System Up Time         : 0 days, 00:01:12.99 (hr:min:sec)
System Up Time (64-bit): 0 days, 00:01:12.99 (hr:min:sec)
Configuration Mode Cfg : …
```
=> Adding support for IXR-e2c

sros/README.md, sros/docker/launch.py
Add the SR-1 FP5 models:
•	SR-1-46S
•	SR-1-92S
•	SR-1x-92S
•	SR-1-24D
•	SR-1-48D
•	SR-1x-48D # => Already existing in vrnetlab
There are 6 versions of the SR-1 ranging in capacity from 2.4T FD to 4.8T FD using either one or two FP5 complexes
There are 3 versions of platform focussed on QSFP-DD 800 only (ends with D)
There are 3 versions of platform focussed on high-density 100G SFP-DD and QSFP-DD 800 (end with S)
=> Add FP5 SR-1 models

Makefile, README.md, freebsd/Makefile, freebsd/README.md, freebsd/docker/Dockerfile, freebsd/docker/backup.sh, freebsd/docker/launch.py, freebsd/download.sh
This is a PR to add FreeBSD support. Once this is approved and verified I will create a PR for `containerlab` as well.
I tested this image with the below `containerlab` topology.
```yaml
name: freebsd01
topology:
nodes:
fbsd1:
kind: freebsd
image: vrnetlab/vr-freebsd:13.2
client1:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.1.2/30 dev eth1
- ip route add 192.168.2.0/30 via 192.168.1.1
client2:
kind: "linux"
image: wbitt/network-multitool:alpine-extra
exec:
- ip addr add 192.168.2.2/30 dev eth1
- ip route add 192.168.1.0/30 via 192.168.2.1
links:
- endpoints: ["fbsd1:eth1", "client1:eth1"]
- endpoints: ["fbsd1:eth2", "client2:eth1"]
```
This image is based on the [OpenBSD](https://github.com/hellt/vrnetlab/tree/master/openbsd) image for `vrnetlab` …
=> Add FreeBSD support

.gitignore, dev-notes.md, sros/docker/launch.py
With release 24, a listen container is added to the netconf container under management-interface. To accommodate this and not break functionality with older releases, add some function that generates different base configurations depending on which release is being used.
Tested with SROS releases 20.10.R13, 21.10.R13, 22.7.R2, 23.7.R2 and 24.3.R1.
=> Version specific config for SR OS

c8000v/Makefile, c8000v/README.md, c8000v/docker/Dockerfile, c8000v/docker/launch.py, common/vrnetlab.py, csr/docker/Dockerfile, csr/docker/launch.py, makefile.include
This is a port of https://github.com/vrnetlab/vrnetlab/pull/341, with the extra containerlab bits added in.
The `vrnetlab.VM` class includes a new `version` property that is populated at build build time. The makefiles for each platform already contain expressions to extract the current version, now this is also included in the final image as an environment variable. This is then used to tweak the behavior of the launch script to specific versions requirements.
=> Add Catalyst 8000v (c8000v)

sros/docker/launch.py
A dirty workaround for potential permissions issue rooted in the fact that originally tftp server that hosts the SR OS config was run by the `tftp` user wity uid/gid = 103/106.
This caused access issues on _some_ installations where SR OS was not able to save the config due to permissions error -- more in this [discord thread](https://discord.com/channels/860500297297821756/1228455734585589892).
It appears to be that the issue is amplifed by the File ACLs added in containerlab some time ago. 
The file ACLs for the tftboot dir are as follows:
```
root@sros:/# getfacl /tftpboot/
getfacl: Removing leading '/' from absolute path names
user::rwx
user:1000:rwx
group::r-x
group:1000:r-x
mask::rwx
other::rwx
default:user::rwx
default:user:1000:rwx
default:group::r-x
default:group:1000:r-x …
```
=> run SR OS tftp server as a root user 

ftosv/README.md, ftosv/docker/launch.py
Newer versions of Dell OS10 have a different *system ready* prompt.
Additionally, it is required to disable ZTD on first boot.
=> Dell OS10: update for newer versions

vqfx/docker/launch.py
The vqfx platform uses a custom version that messes up with the vrnetlab.VM property attribute which has a function getter.
To temporary resolve this clash a new var name is locally declared.
Similar to #193
=> Fix vQFX custom version handling

vmx/docker/launch.py
Issue outlined in: https://github.com/hellt/vrnetlab/issues/192
I have tested this on new vMX images, and it works.
I am opting to re-name the `version` variable in the `VMX_vfpc` class to `junos_version`, which will fix the bug of unintentionally trying to set the getter property in the `vrnetlab.VM` superclass, while maintaining backwards compatibility with the if clause for 14.1R6.4.
We cannot simply use the getter property, as the environment variable is not set by default, causing an exception. I also am not 100% sure whether that is meant to be the same value as the image running, or a different version value.
=> Patch for version bug in VMX_vfpc outlined in https://github.com/hellt/vrnetlab/issues/192

c8000v/README.md, c8000v/docker/Dockerfile, c8000v/docker/launch.py
I have been battling with c8000v image being rendered running but with no ssh access, the ssh just got established, hanged until timeout and disconnected.
I noticied, that this happens when during the image start, the following messages appear on the console
```
% Failed to initialize nvram
% Failed to initialize backup nvram
```
They do always appear in the install phase, but they appear _sometimes_ during the image start (with containerlab) and when they do, I experience the SSH issues.
Not sure how this related, but I have been increasing cpu and ram, to no avail.
Lastly I got the most succesfull runs with setting the virtio net interface, but likely it has nothing to do with the original issue. Will merge this in, but I almost sure that during the autocon1 workshop the issue will …
=> probably  a useless tinkering with the c8000v install process

README.md, vjunosrouter/Makefile, vjunosrouter/README.md, vjunosrouter/docker/Dockerfile, vjunosrouter/docker/init.conf, vjunosrouter/docker/launch.py, vjunosrouter/docker/make-config.sh
Modified the vJunos-switch template for vJunos-router
- Modified Makefile to support vJunos-router regex.
- Modified launch.py for smbios string for VMX type and lab license.
- Modified launch.py class name for vjunos-router instead of vjunos-switch.
Builds successfully with 23.2R1.15. Can be used in Containerlab with kind vjunos-switch and built image.
=> Add vJunos-router support

sros/docker/launch.py
Commit 249b3ca broken SROS distributed model deployment.
```
Traceback (most recent call last):
File "/launch.py", line 1659, in <module>
ia = SROS(
^^^^^
File "/launch.py", line 1407, in __init__
SROS_cp(
File "/launch.py", line 1232, in __init__
ram: int = vrnetlab.getMem(self.role, variant.get("cp").get("min_ram"))
```
There was a change related to getMem and getCpu functions, but only integrated model references were updated.
This updates remaining references for the distributed model case.
=> sros: fix distributed model (getMem, getCpu)

sros/README.md, sros/docker/launch.py
Following example from @hellt to use environment variable to add a disk on Ubuntu :)
This update change the provisioning of additional CF disks from a variable passed inside custom variant type to a variable passed via environment variable, making it compatible with all variants.
=> sros: simplify provision of additional CF disk

routeros/docker/launch.py
Some RouterOS versions didn't detect interfaces quick enough to reliably accept an IP being assigned to ether1. The would reject adding the IP to an interface that didn't yet exist and so would be unreachable via management IP. RouterOS 6.45.9 was particularly bad for this.
This change tells the router to wait for the interface to appear before trying to add the IP. It's probably not be the most elegant solution but it seems to work quite well. Hopefully it'll do until someone else comes up with a better idea.
Fixes #202
Tested on 3 different firmware versions and it appears to work well. See the last 3 rows of the table below.
31 nodes.
| Delay Time | Happy Nodes (got mgmt IP) | Sad Nodes (no mgmt IP) | Firmware Version | Test # | Max Workers |
| --- | --- | --- | --- | --- | --- |
| 0s …
=> Make RouterOS more reliable with management IP config

common/vrnetlab.py, csr/docker/launch.py
The Cisco CSR 1000v build process includes updating the QCOW VM image (good) which results in the management MAC address being stored "somewhere". The build process tries to cope with that, but the current workaround no longer works with release 17.03.04a. Once the container is started, the VM consistently boots with the first interface being GigabitEthernet2 (not GigabitEthernet1) and then everything goes down the drain.
The fix is simple: make the MAC address of the management interface constant (not random). It shouldn't matter as the management MAC address is not visible outside of the container.
However, to be on the safe side, the static MAC address is used only when the child class requests it via the _static_mgmt_mac object property.
=> When required, use a static MAC address for the VM management NIC

routeros/docker/launch.py
On RouterOS 6.x.x with e1000 network driver vlan sub-interfaces with MTU > 1500 do not function properly (they have an MTU of 234 !). On RouterOs 7.x.x they function fine.
I tested with both virtio and vmxnet3 drivers.
* vmxnet3 drivers crashed qemu when the MTU was changed in RouterOS (resulting in a router reboot).
* virtio drivers worked and fixed the issue with MTU. Tested on RouterOS 6.45.9 and 7.12.2. Did not observe any issues while testing.
Mikrotik recommend virtio driver for proxmox (also QEMU based) so it should be fairly safe: https://help.mikrotik.com/docs/display/ROS/CHR+ProxMox+installation
=> Changed RouterOS nic driver from e1000 to virtio to fix RouterOS MTU bug

common/vrnetlab.py, vjunosevolved/docker/Dockerfile, vjunosevolved/docker/launch.py, vjunosevolved/docker/make-config.sh, vjunosrouter/docker/Dockerfile, vjunosrouter/docker/launch.py, vjunosrouter/docker/make-config.sh, vjunosswitch/docker/Dockerfile, vjunosswitch/docker/launch.py, vjunosswitch/docker/make-config.sh, vsrx/docker/Dockerfile, vsrx/docker/launch.py
This PR contains "slim" Dockerfiles, `virtio` disks for all non-EOL Juniper models, and XHCI-based config disks for vJunos models.
All vJunos-based models now have the same Dockerfile, which now contains the `--no-install-recommends` option for apt. This reduces the container image sizes by ~650 MB for every vJunos image.
All non-EOL Juniper devices now run off of virtio-mounted disks, which both increases boot speed and performance, and decreases virtualisation overhead.
I ran a benchmark launching all 4 VM models at the same time, and got the following results:
| Type          | IDE boot time  | `virtio` boot time | Improvement |
|---------------|----------------|--------------------|-------------|
| vSRX 3.0      | 04:24 |     02:34 |         42% |
| vJunosEvolved | 01:39 |     01:08 | …
=> vJunos/vSRX: Slim Dockerfiles, use virtio for boot disk mounting, standardise across Juniper models

cmglinux/Makefile, cmglinux/README.md, cmglinux/docker/Dockerfile, cmglinux/docker/launch.py
CMG Linux is utilized as a DB VM as one of Nokia MAG-C VMs. The image of CMG Linux is released in qcow2 format. Since some of MAG-C tools in CMG Linux are written with systemd or systemctl utilization, then CMG Linux cannot be containerized because docker does not run systemd inside the container. Given this reasoning, the approach to containerized CMG Linux is to create a container to run a CMG Linux VM in the same way Vrnetlab has done.
Initial config is carried out via cloud-init. By default CMG-Linux boots by using a pre-defined cloud-init config drive.
Custom configuration can be added by binding the local `config_drive` directory to `/config_drive` directory in the container.
The accepted structure of `config_drive`is shown below. Any other directories or files not specified below …
=> Initial support for Nokia Mag-C CMG Linux.

sros/Makefile, sros/docker/launch.py
MAG-C boots up in classic CLI, requires some changes to how versions are identified. Also tag the created docker-image with magc so they don't accidentally overwrite other images. Include support patches with a dash in the version for completeness.
=> Distinguish MAG-C images and R2-1 (or similar) patch images

sros/docker/Dockerfile
When deploying a lab with SR OS images built this way, shows 'ValueError: Could not read image format for /sros.qcow2'.
=> Qemu-img command missing after pruning packages

xrv9k/docker/launch.py
xrv9k is way more stable like this, tested with AMD EPYC 7452 cpu and 11 xrv9k booting at same time on version 7.11.2.
=> add xrv9k cpu options

veos/docker/launch.py
veos overloads gen_mgmt with custom forwarding rules (TCP/2022->TCP/22 instead of expected TCP/22->TCP/22).
Removed the overload so that veos uses the common/generic one.
=> remove veos gen_mgmt

c8000v/docker/launch.py, cat9kv/docker/launch.py, csr/docker/launch.py, n9kv/docker/launch.py, xrv/docker/launch.py, xrv9k/docker/launch.py
Relevant to discord thread.
Removal of socat meant that Cisco vrnetlab nodes couldn't be accessed via the management interface due to a non-existent route.
This PR adds the relevant static routes and creates VRFs for nodes if necessary to ensure the default route installed for the management interface doesn't interfere with the default context where the users lab config would usually be.
I've tested everything on Rocky 9.3, I was able to SSH into all nodes with the changes.
=> Add relevant VRF & static routing configuration for Cisco nodes.

common/vrnetlab.py, xrv9k/Makefile, xrv9k/README.md, xrv9k/docker/launch.py
This PR does the following:
- Remove the installation functionality from `vrnetlab.py` and place it in the `launch.py` file for the xrv9k, similar to how the CSR1kv and Cat8kv perform their installation procedure.
- Add an `INSTALL` flag that is able to be passed by the user when building the image, if they wish to disable the installation step
- Update the README to reflect the new `INSTALL` flag.
=> Update & cleanup XRv9k install procedure.

sros/README.md, sros/docker/launch.py
Tested with Release 23.10.R4-1 and should also work with older releases.
=> add pre-defined variant for SecGW - SR-7 with ISA2 MDA

.gitignore, cisco/iol-l2/README.md, cisco/iol-l2/docker/Dockerfile, cisco/iol/README.md, cisco/iol/docker/Dockerfile, makefile.include
@kaelemc I had timeouts for adding the key from your original PR in #256, as well as deprecation warnings
So I change it to use gpg and key fetch with curl. 
Also I change the default naming scheme to be `{registry}/{vendor}_{name}:{version}` to match with how images are named in containerlab
=> Use gpg to manage ppa keys for IOL and change image naming scheme

sros/docker/launch.py
Make qcow pattern match the end of string. Otherwise it may pick up "license" file instead of actual image file.
Proofs.
Build and run the image with the upstream script:
```
$ docker run -it  --privileged --name ixr23-10   vrnetlab/nokia_vsr:23.10.R2
chmod: cannot access '/tftpboot': No such file or directory
2024-10-10 04:35:39,114: launch     DEBUG    acting flags: username 'vrnetlab', password 'VR-netlab9', connection-mode 'vrxcon', variant 'sr-1'
2024-10-10 04:35:39,114: launch     DEBUG    Environment variables: environ({'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': 'cb388c2301bf', 'TERM': 'xterm', 'HOME': '/root', 'LC_CTYPE': 'C.UTF-8'})
2024-10-10 04:35:39,115: launch     INFO     Parsed SR OS version: SROSVersion(magc=False, …
```
=> fix sros qcow regex pattern

fortigate/Makefile
VR_NAME is not defined in the Make file.
The docker build will fail as the image tag "-t $(REGISTRY)vr-$(VR_NAME):$(VERSION)" requires VR_NAME to be defined.
=> Adding VR_NAME otherwise it will not build

c8000v/Makefile, csr/Makefile, makefile.include
Removed whitespaces from makefile.include and fixed CSR and c8000v which had the VR_NAME variable that were not set.
=> Fix CSR1000v and c8000v

cisco/iol/docker/entrypoint.sh
Relevant to https://github.com/srl-labs/containerlab/pull/2239.
This changes the IOL entrypoint script so that the environment variable `IOL_PID` is used to select the launch PID for the IOL binary.
=> Use env var passed from containerlab for IOL launch PID

csr/docker/launch.py
Change the default value of 9 (allowing `GigabitEthernet2 -> GigabitEthernet10` for data interfaces) to 31 (`GigabitEthernet2 -> GigabitEthernet32`).
Closes https://github.com/hellt/vrnetlab/issues/273
=> Increase max_nics for cisco csr

makefile.include
Link that points to github issues points to the original vrnetlab project. This PR changes the link so that the link points to this fork.
=> Update Github issues link in makefile.include

fortigate/docker/launch.py
Fortigate issues a free trial license that is tied to the UUID of the VM. There is 1 license per account
The UUID determines the device serial number; it can be viewed in the FortiCloud web site under "Asset Management"
=> Add env variable "FORTIGATE_UUID" to set the VM UUID for license matching

cisco/iol/docker/Dockerfile
As the title says. Replace the GNS3 PPA with the netdevops.fury gemfury repo which hosts the custom build of IOUYAP that @DanPartelly has made.
Will take it out of draft status once testing is complete.
=> Replace GNS3 PPA with netdevops gemfury repo (for IOUYAP) in IOL Dockerfile

exos/Makefile, exos/docker/Dockerfile, exos/docker/launch.py
This current implementation was tested and is working with the following images (EXOS images are easily found in the official Extreme Networks github page):
`EXOS-VM_v22.4.1.4-disk1.qcow2`
`EXOS-VM_v32.6.3.126.qcow2`
This implementation also partially worked with older versions of EXOS (tested with `EXOS-VM_v16.1.1.4-disk1.qcow2` and `EXOS-VM_v21.1.1.4-disk1.qcow2`). The bootstrap and initial configuration were successfully applied, and SSH access was possible. However, testing showed high latency and packet loss during ping tests between hosts.
If anyone with more experience in emulating these systems could provide insights or suggestions to help resolve the connectivity issues, it would be greatly appreciated.
Notes:
- The startup configuration functionality is implemented based on …
=> Add support for EXOS

README.md, common/vrnetlab.py, vjunosevolved/docker/init.conf, vjunosevolved/docker/launch.py, vjunosrouter/docker/init.conf, vjunosrouter/docker/launch.py, vjunosswitch/docker/init.conf, vjunosswitch/docker/launch.py
This PR adds pass-through as a mode for management interfaces. The default mode for management interfaces remains host-forwarded (which is the previous and only mode supported for management interfaces).
The pass-through mode functions by simply creating yet another tc mirred interface for the NOS VM management NIC instead of binding it to a user-mode, host-forwarded one.
The main advantages of transparently passing management traffic is:
- All protocols/traffic pass through and are visible from both the containerlab host and between vrnetlab containers, allowing for labbing to include management connectivity, e.g. via a firewall
- The NOS configuration accurately reflects the management IPs of the vrnetlab nodes. This is very useful when generating configurations from a source of truth. …
=> Pass-through/transparent management interfaces

common/vrnetlab.py, ftosv/README.md, ftosv/docker/launch.py
* Wait while system gives "loading" prompt
* Add note on qcow2 compression, reduced image to ~30% in my case for 10.5.6.6:
```-rw-r--r--  1 jvanbemmel jvanbemmel 2336227328 Oct 31 08:54 dellftos.10.5.6.6.qcow2```
More general changes:
* Refactor management IP network settings, make them configurable
* Change Dell OS10 management link to private 169.254.127.0/24 range, to minimize chance at overlap with other configs ( original 10.0.0.0/24 is way too common ... )
* Forward only the TCP ports used by the platform, not the full set of those used by all other platforms
* Address warnings caused by format strings to logger
=> Dell OS10 improvements

makefile-install.include
At some point we changed to `registry/vendor_platform:version` naming scheme.
`makefile-install.include` wasn't updated to reflect this, which broke xrv9k (and maybe other platforms) which depend on this file for the install process as of current.
This PR simply changes the naming scheme (and variable names) in `makefile-install.include` to match the new naming scheme.
Tested with XRv9k to confirm it works.
=> Fix makefile-install.include naming schema

xrv9k/docker/launch.py
IOS XRv 24.2.2 does not show call-home configuration.
waiting for the linecard to give status IOS XR RUN works instead.
Tested with 24.2.2, 7.11.2 and 7.9.2
=> Fix launch.py for ios xrv >7.1

vsrx/docker/init.conf, vsrx/docker/launch.py
This PR adds supports for transparent management interfaces on the vSRX platform. This means all currently supported Juniper NOSes will have support for this feature (vMX and vQFX are legacy platforms).
=> vsrx: Add transparent management interface mode compatibility

c8000v/docker/launch.py, common/vrnetlab.py, dell_sonic/Makefile, dell_sonic/docker/launch.py
caveat: despite setting the v6 address to eth0, it is either overwritten later on by the system or is never applied in the first place
=> Dell sonic transparent mgmt support

README.md
Overall some minor items in the Readme content.
* Fix typo(s)
* Change quoted area to an Alert (a.k.a. admonition)
* Replace a broken netdevops.me hyperlink with an archive.org copy of that page
* Move the Connection Mode list into a table
* Various wording and sentence changes (admittedly my take and can be adjusted)
* Markdown linting-esque changes
* (full MD linting and GH Actions for another PR!)
* Surround MD headers with white space
* Break long MD lines into shorter lines
I'm open to feedback and any tweaks/changes.
=> Some Readme content edits

aoscx/README.md, aoscx/docker/launch.py
Seems that newer versions of AOS-CX requires more CPU and RAM to work well (despite it can boot with the old, lower values, some problems can happen in case of huge config)
=> AOS-CX: Update CPU and MEM values for newer versions

common/vrnetlab.py
File-based signalling interface to send a qemu-monitor **system_reset** command to all or a subset of the VR component VMs . This acts like an hardware reset button without disrupting existing qemu VM properties (interfaces, disks...). It should recover a VM in hang state without need to re-deploy the whole clab topology. Also useful in some test scenarios.
Create a file named "reset" under the root path of the container. There are two possibilities:
- **To reset the VR**, create an empty file:
eg: `sudo docker exec container_name_or_id touch /reset` -> reset all component VMs
- **To reset specific VMs**, include a comma separated list of VM numbers in the file contents.
eg: `sudo docker exec container_name_or_id sh -c 'echo "0" > /reset'` -> reset VM 0
eg: `sudo docker exec …
=> backdoor to reset VR or specific VMs

cat9kv/docker/launch.py
The VRF for the static default management route was incorrectly set to `clab-mgmt` which is the name for the management VRF on other IOS-XE devices.
Cat9kv automatically creates it's own management VRF with the 'Mgmt-vrf' name. 
I probably made an erroneous copy and paste here. Apologies 😅
=> Fix mgmt route VRF name on cat9kv

vjunosevolved/docker/init.conf
plus remove config for ZTP as per console log message:
```
2024-12-31 09:11:40 INFO: ZTP: remove "chassis auto-image-upgrade" from config to abort ZTP
```
=> vJunos-EVO: remove error in init file that prevents loading it

routeros/README.md, routeros/docker/Dockerfile
The typing change caused an issue when starting the container:
```
Traceback (most recent call last):
File "/launch.py", line 11, in <module>
import vrnetlab
File "/vrnetlab.py", line 860, in <module>
def cidr_to_ddn(prefix: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```
Updating the ubuntu version allow to be more up to date and use newer python version.
=> Fix routeros 

viosl2/Makefile, viosl2/README.md, viosl2/docker/Dockerfile, viosl2/docker/launch.py
All necessary changes needed to make the vios files work for vIOSL2.
Added new directory `viosl2` (was quicker than changing the vios code and making it work for vios and viosl2 ;-)).
- Adapt NAME to `vIOSL2`
- Adapt comments and version regex for viosl2 image file
Added `procps` to base bookworm image for troubleshooting purposes.
- Increase memory for IOSvL2 image from 512 to 768
- Change expected prompt from `Router>` to `Switch>`
- Adapt initial configuration for L2 switches
All changes needed to describe viosl2 instead of vios.
Successful tests with image `vios_l2-adventerprisek9-m.ssa.high_iron_20200929.qcow2` (CML reference platform). Tested with example topology file shown in `README.md` and also with a 10 node network with core, distribution and access switches incl. access …
=> Add Cisco vIOS L2 support

n9kv/docker/Dockerfile
The python script to generate the image needs qemu-img which is in qemu-utils
=> Update Dockerfile to install qemu-utils

aoscx/docker/Dockerfile, aoscx/docker/launch.py
Encountered hardware issues similar to the one reported on #171 -
this PR is solving the issue in my case.
@JJ-empowered are you able to test in with your device and see if this solves also your issue?
=> AOS-CX: Update base image and cpu

vqfx/Makefile
In the last line is calling the variable $(VR_NAME) but it wasn't defined before so i update the variable NAME to VR_NAME
=> Update vqfx Makefile

common/vrnetlab.py, csr/docker/launch.py, dell_sonic/docker/launch.py, routeros/docker/launch.py, sros/docker/launch.py
This small series of commits is adding DHCP and static MAC support for the management interface.
Primary focus was to be able to test the Zero Touch Provisioning feature available on SONiC which relies on DHCP in its first stage.
Basic Containerlab Example:
```
name: sonic-ztp
prefix: ""
mgmt:
network: mgmt
ipv4-subnet: 172.80.80.0/24
topology:
defaults:
kind: dell_sonic
env:
CLAB_MGMT_DHCP: "true"
CLAB_MGMT_PASSTHROUGH: "true"
kinds:
dell_sonic:
image: vrnetlab/dell_sonic:4.4.0
nodes:
sonic01:
env:
CLAB_MGMT_MAC: "0c:00:01:01:01:01"
sonic02:
env:
CLAB_MGMT_MAC: "0c:00:01:01:01:02"
ztpserver:
kind: linux
image: alpine-s6-ztpserver:latest
mgmt-ipv4: 172.80.80.10
binds:
- config/ztpserver/dnsmasq.conf:/etc/dnsmasq.conf
```
This topology defines a custom management network and enables the …
=> DHCP and static MAC support for management interface 

vjunosevolved/README.md, vjunosevolved/docker/Dockerfile, vjunosevolved/docker/launch.py, vrnetlab-base.dockerfile
Juniper recently released vJunosEvolved 24.2, which now requires UEFI boot, and now comes in two variants, BT and BX chipset support.
The Dockerfile of vjunosevolved has been revamped to use the vrnetlab base image.
The `ovmf` package for UEFI BIOS has been added to the vrnetlab base image (this PR requires a new version to be published). I used a future 0.2.1 version in the vJunosEvolved Dockerfile.
=> Add support for vJunosEvolved 24.2 and up

vstc/Makefile, vstc/README.md, vstc/docker/Dockerfile, vstc/docker/launch.py
vSTC is weird in that you have to reboot to apply config. Since there is no DHCP server to apply the passthrough address from clab, we enter the IP addressing manually. Then reboot the node.
This node has transparent mgmt passthrough force enabled, will not connect correctly with the QEMU NAT.
Unfortunately this means the node boot time is doubled, but this quick and dirty method does the trick.
=> Implement Spirent vSTC

pan/Makefile
Fixes #332. Simplified the regex so it works with both no suffix and suffix version numbers.
```
Building docker image using PA-VM-KVM-10.2.10-h12.qcow2 as vrnetlab/paloalto_pa-vm:10.2.10-h12
...
Building docker image using PA-VM-KVM-10.2.10.qcow2 as vrnetlab/paloalto_pa-vm:10.1.11
```
=> PAN-OS: Handle version number suffix

common/vrnetlab.py, sros/docker/launch.py
- Changed the env var naming for the SROS `DEBUG_SCRAPLI` to `LOG_SCRAPLI`. It fits the purpose of the env var closer.
- Added a global `DEBUG_SCRAPLI` env var (in vrnetlab.py). If it's set to `"true` then Scrapli logging will be on `logging.DEBUG` which is much more verbose (shows all channel I/O).
=> Add `DEBUG_SCRAPLI` env var

openwrt/README.md, openwrt/docker/Dockerfile, openwrt/docker/launch.py
This PR revives and refactors the existing OpenWRT support in `vrnetlab` for Containerlab
Changes include:
- Restored and updated the OpenWRT image to be functional again
- Added support for overlay persistence via `/overlay`
- First-boot detection to set root password
- Separated LAN (`eth2`) and MGMT (`eth0`) interfaces
- MGMT interface can operate in passthrough or non-passthrough mode
- Automatic configuration of:
- `/etc/config/network` (MGMT interface, routes, br-lan ports)
- `/etc/config/firewall` (MGMT zone)
- `/etc/hosts` and host routes for package domains
- Optional auto-install of packages via `PACKAGES` env variable
- Automatic `opkg update` and upgrade on boot
This refactored OpenWRT image is now better compatible with …
=> Fix and extend OpenWRT vrnetlab image for Containerlab compatibility

common/healthcheck.py
The healthcheck.py wasn't executable anymore. Fix that.
=> bring back python3 shebang to unbreak healthcheck.py

huawei_vrp/docker/launch.py
Adds the 'undo dcn' command during the Huawei bootstrap process to remove potential residual configurations (e.g., DCN auto-configuration) that may come bundled with the image. This ensures a clean initial state for provisioning and avoids interface conflicts.
=> feat(huawei): add 'undo dcn' to bootstrap to clear residual  configs

cmglinux/docker/Dockerfile, freebsd/docker/Dockerfile, openbsd/docker/Dockerfile, ubuntu/docker/Dockerfile
The Dockerfile for these images would copy in the image file then run `qemu-img resize IMAGE DISK_SIZE`, because of the way container layers work that means you end up with two copies of the image in the container, one of which is unusable. This effectively doubles the container size.
Also I added `--no-install-recommends` as without it hundreds of unneeded packages such as fonts are installed.
This takes the Ubuntu image from 2.24GB to 950MB
=> Reduce container size

ocnos/docker/launch.py
According to https://containerlab.dev/manual/kinds/ipinfusion-ocnos/ the virtualisation should support up to 144 interfaces.
The best I was able to manage was 62 (eth0 mgmt to eth62) before it refused to boot. It appears that this limit relates to the QEMU Machine/PCI limit
To go beyond 62 (I would like to get to at least 64!) I think we need to identify alternative QMEU options to increase the number of PCI buses created - but that's a challenge for another time.
This change increases the maximum number of 62, and I have included a test artefact validating both creation and also packet flow of eth1 and eth62 between two OcNOS instances
[CONTLAB-OCNOS-MAXPORTS.txt](https://github.com/user-attachments/files/20805739/CONTLAB-OCNOS-MAXPORTS.txt)
=> OcNOS - Increase max nics to 62

n9kv/docker/launch.py
If a command that requires user input, such as `copp profile strict`, is present in the startup config file of a n9kv instance, config deployment will freeze once it pushes that command.
Setting `terminal dont-ask` before pushing the config skips the prompts:
```
n9kv-test# terminal ?
dont-ask          Don't prompt for confirmation, do what the command indicates
```
Tested with n9kv 10.3.1 and 10.3.8.  The command appears to be available in all NXOS versions: [here's version 6 from 2014](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/command_reference/config_612I22/b_n9k_command_ref/b_n9k_command_ref_chapter_010110.html#wp3962612674)
Fixes https://github.com/hellt/vrnetlab/issues/373
=> Handle interactive config commands on n9kv

xrv9k/docker/launch.py
I'm not sure if this is an issue with all XRv9k versions, but it happens at least on the 6.6.3. 
Without this fix, a SSH connection fails with an error in the log and is not possible, cause the SSH Host Keys are missing
One could also argue that there shouldn't be a need for the RSA-Host-Key, cause most SSH clients deny the connection, but I included it nevertheless for legacy reasons.
=> xrv9k: Fix broken SSH initialization

huawei_vrp/docker/launch.py
Modified huawei_vrp launch.py to extract VRP version, set specific CPU and RAM values for different VRP versions and added an option to run version specific commands during bootstrap configuration.
Added some more detailed comments. Increased some sleep timers (more reliable when starting a lot of container VMs at once because some commands take multiple seconds to get accepted).
Removed/commented the "commit" command in launch.py because it doesn't work for R23 version for whatever reason. But with mmi-mode the system does an auto-commit at final quit (when bootstrap is leaving the router). So, nothing is lost.
Tested successful with ne40e-V800R023, ne40e-V800R022, ne40e-V800R011C00.
=> Optimized huawei_vrp launch.py

cisco/cat9kv/Makefile, cisco/cat9kv/README.md
Cat9kv can be built with either the UADP or Q200 emulated ASIC. This PR adjusts the regex in the Makefile to be more in line with IOL-XE which allows custom tags to be prepended to the version. This also includes a note in the readme to indicate that the custom image tagging is possible.
=> Adjust regex for Cat9k build in Makefile
