srl-labs/vrnetlab

- vmx/Makefile
- vmx/README.md
- vmx/docker/Dockerfile
- vmx/docker/launch.py
This PR adds vmx support for connection mode (aka docker networking)
* plus addresses issues of image auto-upgrade killing cli session abruptly
* added hostname config
* added user/password params
* added gNMI port 57400
* bumped dockerfile to ubuntu:20.04 + added `tcpdump` and `ps`
> Vmx with connection mode and fixes

- common/vrnetlab.py
- sros/README.md
- sros/docker/launch.py
merge after #10 with changing base to `master`
close #13
close #12 
close #11
> Sros improvements

- sros/README.md
- sros/docker/launch.py
allow sros custom variants to be defined by a user
> Sros custom

- common/vrnetlab.py
- sros/docker/Dockerfile
- sros/docker/launch.py
- vmx/docker/Dockerfile
- vmx/docker/launch.py
- xrv/docker/Dockerfile
- xrv/docker/launch.py
- xrv9k/docker/Dockerfile
- xrv9k/docker/launch.py
> Macvtap based networking

- common/vrnetlab.py
- sros/docker/launch.py
LACP friendly and no-additional-packages datapath using tc
ref: https://gist.github.com/networkop/4e04ef70b8c5f96d20cdf73ea32900d1#gistcomment-3638209
> tc based datapath

- common/vrnetlab.py
- sros/docker/launch.py
- vmx/docker/launch.py
- xrv/docker/launch.py
- xrv9k/docker/launch.py
sets boot delay for sros, vmx, xrv, xrv9k
BOOT_DELAY env var set to seconds of delay
> added boot delay env var handling

- common/vrnetlab.py
- veos/Makefile
- veos/docker/Dockerfile
- veos/docker/launch.py
> added veos docker native support

- sros/docker/launch.py
> added dummy interface for sros ixr6 variants

- sros/docker/launch.py
plus fixed upper/lower case in variant names
> added default cpu/ram for custom variants

- nxos/docker/Dockerfile
- nxos/docker/launch.py
First step to make nxos working on containerlab.
> fix nxos launch.py and Dockerfile

- .gitignore
- pan/Makefile
- pan/README.md
- pan/docker/Dockerfile
- pan/docker/launch.py
In support of hopefully adding this to containerlab soon... :)
> PA-VM Support

- common/vrnetlab.py
- n9kv/Makefile
- n9kv/README.md
- n9kv/docker/Dockerfile
- n9kv/docker/launch.py
* Adds support for N9kv
* I'm fairly sure the bios file is not necessary now but I very much recall it being "necessary" before... I do know it does not *hurt* so figured id leave it in...
* Also fixes a screw up from yesterday for the "gen_nics" delay fixup (CLAB_ENV_INTFS vs CLAB_INTFS)
> N9kv Support

- routeros/docker/Dockerfile
- routeros/docker/launch.py
Added the ability to push configs using Mikrotik's FTP upload capabilities and automatically importing config from files that end in .auto.rsc.
Also fixed setting the password for the user 'admin' as we need to set it instead of adding the command
> Mikrotik Routeros improvements

- ftosv/Makefile
- ftosv/README.md
- ftosv/docker/Dockerfile
- ftosv/docker/launch.py
- Used `nxos` and `n9kv` as reference with FTOS specific changes under launch.py
- Used S5248 platform based .qcow2 disk for image build.  All other available virtualization platform options should work the same.
> Dell FTOS10v Support

- sros/docker/launch.py
> added bof save

- vqfx/docker/launch.py
I put in some really rudimentary support for spraying in set style JunOS commands. It's kinda hacky TBQH.
> feat: initial support for spraying in set commands

- vqfx/Makefile
- vqfx/docker/Dockerfile
- vqfx/docker/launch.py
fix #72 
note, that 20.2 downloaded from juniper contains 19.4 image. This will break bootstrap script, as the version container in the file name mismatches the real sw version
> added version detection for vqfx

- vmx/docker/launch.py
- vmx/vmx-extract.sh
> [vmx] added stratup config and improved version matching

- n9kv/Makefile
Hi ! I was trying to find the correct tag for my personal project and found this file had a missing parenthesis. I hope that helps.
> Missing parethesis in the file

- .gitignore
- csr/docker/launch.py
- ftosv/README.md
- ftosv/docker/launch.py
- n9kv/docker/launch.py
- nxos/docker/launch.py
- veos/docker/launch.py
- xrv/docker/launch.py
- xrv9k/docker/launch.py
This PR is a companion to one for Containerlab to solve most of [https://github.com/srl-labs/containerlab/issues/973](973).
Nodes:
- CSR1000v
- vEOS
- NXOS
- N9KV
- XRV
- XRV9K
- FTOSV
The only nodes it doesn't update is PAN.
I also updated the gitignore file to exclude the copied over files (healthcheck.py and vrnetlab.py) to make it cleaner with git
> 973 startup config

- common/vrnetlab.py
- sros/docker/launch.py
> Multi LC implementation on Master Branch

- common/vrnetlab.py
Ensure PCI bus index always starts from 1 even though in multi lc mode
> Correction for PCI bus mapping in Multi LC

- common/vrnetlab.py
Reduce dummy PCI creation by limiting max ethernet index based on ethernet index range of each line card.
> Reduce dummy PCI creation

- sros/docker/launch.py
Co-authored-by: Jeroen van Bemmel <jeroen.van_bemmel@nokia.com>
> added line card config helper and sr-1x-48D

- pan/docker/launch.py
Add feature to run startup scripts (startup-config.cfg) when booting pan-vr. This is implemented based on @nlgotz work in the commit linked below[1]. I have verified that config file is correctly applied.
[1] https://github.com/hellt/vrnetlab/commit/607bae706b4d0720cd97ccaff91ff1d63561f565
> Add Startup Script capabilities to pan-vr.

- common/vrnetlab.py
- sros/docker/launch.py
example:
distrubuted:
```
name: sros01
topology:
nodes:
sr1:
kind: vr-sros
type: sr-1e
license: sros22.lic
env:
CP_MEMORY: 6
CP_CPU: 4
LC_MEMORY: 6
LC_CPU: 4
```
integrated:
```
env:
MEMORY: 8
CPU: 4
```
> Added CPU and MEM provisioning from env vars for SR OS

- sros/README.md
- sros/docker/launch.py
I moved almost everything from #71, except for connectors provisioning, as I wanted to do that separately
> Patches from #71

- Makefile
- README.md
- config-engine-lite/configengine
- topology-machine/topomachine
- vsrx/Makefile
- vsrx/docker/Dockerfile
- vsrx/docker/launch.py
Hi,
This PR adds support for Juniper vSRX3.0 (https://supportportal.juniper.net/s/article/Overview-of-the-available-virtual-SRX-models-vSRX-and-vSRX-3-0?language=en_US).
> Add Juniper vSRX3.0 support

- sros/docker/launch.py
'lsc' is a typo, but the entire line can be omitted
> Update launch.py - remove typo

- vsrx/docker/launch.py
Cherrypicking and superseding #118 and #119
* Improved commit phase (it seems that sometimes the "commit and-quit" is stuck)
* Management VRF for fxp0 traffic (and default route for it)
(@hellt unable to do a direct fork from #118, so I did a cherrypick from both #118 and #119)
> vSRX fixes and improvements

- sros/Makefile
Uses system environment variables for HTTP and HTTPS proxy if set
> Updated proxy section of makefile

- vjunosswitch/docker/launch.py
> fix #144 (vJunos-switch fails to create initial config, if startup-config is none)

- sros/docker/Dockerfile
- use debian bookworm base
- do not upgrade debian during build
- remove ipy package (not used)
> Update SR OS dockerfile

- vsrx/docker/launch.py
vSRX - adding code to launch.py to load startup config. 
topology:
nodes:
node:
kind: vr-vsrx
startup-config: myconfig.txt
> vSRX - adding code to launch.py to load startup config

- openwrt/Makefile
- openwrt/README.md
- openwrt/docker/Dockerfile
- openwrt/docker/launch.py
- openwrt/download.py
this PR is to make OpenWRT working again:
- fixed the download.py, added support for minor versions eg 23.05.3, unzip is now part of the download.py instead of the Makefile, download.py will skip the download if file is allready downloaded.
- switch to alpine instead of debian to reduce the image size by 814 mb
- fixed launch.py, replaced argparse with click(support for environment variables - username, password and connection_mode) default connection mode is tc
- updated the readme
BR
Takalele
> Fixed OpenWRT

- sros/docker/Dockerfile
- sros/docker/launch.py
> Sros config save defaults

- xrv9k/docker/launch.py
The default credentials of admin:admin have been removed from the credentials list and I've altered how the login process happens, the 0th set of credentials in `self.credentials` is used, as there should only be one set of credentials populated at any time (the default is clab:clab@123, or credentials are set by the user as environment variables).
On attempted login, we now check if the login was successful and if we are at the `ios#` prompt. If this was a success `xr_login` is set to True so the bootstrap process can now begin, previously to check if bootstrap can begin the script checked for the `ios#` prompt. If it were kept this way there would be a redundant check occurring for the same thing.
I also removed the Gig0/0/0/0 check as part of the bootstrap process as it takes a …
> Fix XRv9k login process, and remove Gig0/0/0/0 check 

- common/vrnetlab.py
> Initialise min_nics variable to 0.

- aoscx/docker/launch.py
> AOS-CX: add default route on mgmt interface

- vjunosevolved/docker/init.conf
> vJunosEVO: add mgmt def route

- ftosv/README.md
- ftosv/docker/Dockerfile
- ftosv/docker/launch.py
* default route
* version caveats
* use slim container image
> Updates for Dell OS10

- sonic/docker/backup.sh
> Fix sonic vm backup script

- vmx/docker/launch.py
> Remove extra gnmi socat for vmx

- ftdv/docker/launch.py
FTDv would previously hang on install and hence image couldn't be built.
- The FTDv install class was using the default QEMU CPU args (which would be 1vCPU). The FTDv requires 4. SMP args have been moved into the correct place now.
- Added a `login_ready` variable which gets set to true once we should start looking for the login prompt, previously the login prompt was being picked up too early in the boot process. This is only relevant for the install process.
- Changed the prompts we look for as telnetlib is unreliable and doesn't catch the prompt sometimes. Seeing about 80% success rate. 
Telnetlib still sometimes doesn't catch the login/password or `>` prompt. The node just has to be restarted until it works. Hopefully scrapli will fix this (coming soon™).
> Fix FTDv bootstrap

- vios/Makefile
- vios/README.md
- vios/docker/Dockerfile
- vios/docker/launch.py
- Motivation: low memory footprint compared to IOS XE/XR.
- More information is in the README.md.
> Add Cisco vIOS support

- ftosv/README.md
On 10.5.6.5 the admin/admin login didn't work for me
> Add note about linuxadmin account

- n9kv/docker/launch.py
- Update the memory to 10GB.
- Update the number of CPUs to 4.
[Cisco documentation reference](https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/105x/configuration/n9000v-9300v-9500v/cisco-nexus-9000v-9300v-9500v-guide-release-105x/m-overview.html)
> Update memory and cpu count for cisco/n9kv to match cisco documentation

- ocnos/docker/launch.py
as per https://github.com/hellt/vrnetlab/issues/177#issuecomment-2002308711
fix #177
> give ocnos some time to boot in the login routine

- ocnos/docker/Dockerfile
- ocnos/docker/launch.py
- Fixed the issue where SSH was not working on OcNOS
- Updated the Docker image to Debian Bookworm
Tested with `OcNOS-SP-PLUS-x86-6.5.2-101-GA.qcow2`.
Full [boot log](https://gist.github.com/trustywolf/47021c74a4390cef262caa9a81efb0bd).
> Fix for OcNOS 6.5.2-101

- sonic/docker/launch.py
fix https://github.com/srl-labs/containerlab/issues/2369
> increase maximum nics for sonic vm

- aoscx/docker/Dockerfile
- aoscx/docker/launch.py
- ocnos/docker/Dockerfile
- ocnos/docker/launch.py
- routeros/README.md
- sonic/docker/launch.py
- veos/docker/Dockerfile
- viosl2/Makefile
- viosl2/README.md
- viosl2/docker/Dockerfile
- viosl2/docker/launch.py
- vjunosevolved/docker/init.conf
- vmx/docker/Dockerfile
- vqfx/Makefile
- vqfx/docker/Dockerfile
Relevant to #306.
I think I covered most things. Wouldn't count it out that I mucked something up though :)
 
Might wanna check over `pyproject.toml`. Wasn't sure what to do there.
> Resolve merge conflicts for #306

- common/vrnetlab.py
- csr/docker/launch.py
- dell_sonic/docker/launch.py
- routeros/docker/launch.py
- sros/docker/launch.py
> Merge conflicts #2

- huawei_vrp/docker/Dockerfile
Copied Dockerfile from xrv9k/docker/Dockerfile to huawei_vrp/docker/Dockerfile which successfull allows the make for Huawei VRP now
> Huawei VRP support

- pan/docker/Dockerfile
> Fix panos dockerfile

- vstc/docker/launch.py
Check per AF if the mgmt IP is undefined, or DHCP.
In these cases we don't need to push any configs for them.
> vSTC: Fix mgmt IP issue.

- sros/docker/launch.py
fixed little issue in SROS release identification.
> little fix for SROS

- openbsd/Makefile
- openbsd/README.md
- openbsd/download.sh
Closes https://github.com/hellt/vrnetlab/issues/353
@de-cix-role
> Update OpenBSD download script, tagging logic and documentation

- vqfx/docker/launch.py
Add static route to fix issue #370
> fix: issue #370

- common/vrnetlab.py
- n9kv/docker/Dockerfile
- `CLAB_MGMT_INTF` override the default manangement interface (default: `eth0`)
- `CLAB_INTF_PREFIX` override the data interface prefix (default: `eth`)
> Add environment variables to override the management interface and data interfaces prefix

- makefile.include
> Fix docker-push-image target to upload the correct image tag
